### ISSUE TITLE
Configuration dialog Updates

### ISSUE THREAD

**Issue by bflanagin** [LeafletBomb/leafletbomb#1]
The setup for companies was thrown together as quickly as possible. Now that we are nearing the MVP deadline these are the things that need to be accomplished

- [ ] Create a multi form quick setup wizard for new accounts

- [x] Move spokes persons / team to their area

- [x] Change Side bar to reflect the options for the area you are in. (i.e. Settings or standard)

**Comment by bflanagin** [comment]
Two down one to go

**Comment by ryanleesipes** [comment]
Related to #31

**Comment by ryanleesipes** [comment]
Sorry, meant to link to #21

**Comment by bflanagin** [comment]
Done.
