### ISSUE TITLE
Company and Contact Info Not Saving

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#10]
For some reason changes to Company info doesn't save, and as the master of all things I cannot set up the contact info.

**Comment by bflanagin** [comment]
Seems to work now

**Comment by bflanagin** [comment]
Fixed Company side, Master account settings were moved to the Team area and I'm currently reworking that area.

**Comment by ryanleesipes** [comment]
Great!

**Comment by bflanagin** [comment]
Flipping team code was the typical first draft garbage. Fixed now.
