### ISSUE TITLE
Distribution List Analytics

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#13]
Should be able to view open rate and click-through rate (to view full press release) through the interface, per press release.

**Comment by bflanagin** [comment]
huh?

**Comment by ryanleesipes** [comment]
For each press release that is sent to a distribution list (via Email), you should be able to see which influencers viewed it, and which clicked to see the full press release on the website (via a link in the Email).

**Comment by bflanagin** [comment]
This is almost working. It needs testing.

**Comment by ryanleesipes** [comment]
In order to test this, we need to make sure Email is working. Have you tested it after your changes? I'm using an SMTP service and am not sure if the service is working.

**Comment by bflanagin** [comment]
Worked for me last night. Using the lastest version. BUT, the hardcoded stuff might be in the way. #33

**Comment by ryanleesipes** [comment]
Alright, with the reply to set, Sendgrid works. So we know we need that. I never saw any analytics stuff show up on mine (like who had seen and such). But yours is working, so maybe my machine is just rejecting the tracker stuff.

**Comment by bflanagin** [comment]
Yeah, its a funny how many things block the tracker bits and other tricks of the trade. I think we should assume the audience is going to have something to keep most trackers from working.

**Comment by ryanleesipes** [comment]
We'll mark this closed and see what happens when we get this deployed on some full-time servers.
