### ISSUE TITLE
Single Tenant Instance

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#16]
Eventually we may want to make an Agency version of Leaflet Bomb. But we should cut away as much as we can from this version. An instance should be single tenant (so one company). This is going to be important for displaying the "newsroom"

**Comment by bflanagin** [comment]
lol, One way or the other brother, you wanted to put your company on my instance.

**Comment by bflanagin** [comment]
So fun...well not sure if its fun fact. The multi tenant version was broken for the most part. Should be hidden and disabled.
