### ISSUE TITLE
Reroute after setup

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#21]
After creating a user account, reroute the user to company setup.

After creating, still prompted to create one:
![become_marketer_after_login](https://user-images.githubusercontent.com/2141621/31402746-28b4a500-adb4-11e7-832b-81c774e3c260.png)

Should be shuffled to this page:
![create_company](https://user-images.githubusercontent.com/2141621/31402797-50fc392e-adb4-11e7-82e6-e386f28bc51d.png)

**Comment by ryanleesipes** [comment]
After company setup - should probably be prompted for personal account info, such as picture, phone, and Email.

**Comment by bflanagin** [comment]
Going to add pop ups to encourage users to do that.

**Comment by bflanagin** [comment]
The pop up is all scripted up to disappear when the setup is complete. It also has a bulleted list that counts down as you finish the steps. 

Looks ugly though.

![screenshot from 2017-10-14 18-31-14](https://user-images.githubusercontent.com/10382037/31580178-e92c7734-b10d-11e7-9839-8bf2ecfac490.png)

**Comment by bflanagin** [comment]
Closing, All that this requires is a little visual update, I'll get that done as soon as I can. But the bug is fixed.
