### ISSUE TITLE
Fix Spokesperson Box

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#24]
Not very useful at the moment, needs to be cleaned up and have some content adjusted/added.

![spokesperson_fix](https://user-images.githubusercontent.com/2141621/31403382-29beca82-adb6-11e7-9a8b-fe0d8fdaea04.png)

**Comment by bflanagin** [comment]
Going to have to give me more info. thats too vague even for me.

**Comment by ryanleesipes** [comment]
I got this, just putting it in for my own tracking (I assigned it to me). I'll assign the ones to you that need your attention.

**Comment by ryanleesipes** [comment]
@bflanagin to expand I'm looking to add the spokesperson's name and phone number.

**Comment by ryanleesipes** [comment]
Whoops, forgot to change branches for fixing some of this, initial work going in topicons branch.

**Comment by bflanagin** [comment]
Fixed
