### ISSUE TITLE
Assets give no indication they are uploading/uploaded

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#27]
When adding assets to a press release, there is no indication that they are uploading or uploaded. This will probably frustrate users.

**Comment by bflanagin** [comment]
Added a loading spinner to the asset loading area. It happens fast so we'll need more testing before we can close it.

**Comment by ryanleesipes** [comment]
That would be okay if it would show the asset after it is uploaded.

**Comment by ryanleesipes** [comment]
It also won't upload as quickly on a remote server.

**Comment by bflanagin** [comment]
Yeah I can see the spinner for a brief second and then the image is loaded in its place. 
This is the upload image function for future reference. 

`
   'change .featuredImgInput': function(event, template) {
                    var files = event.target.files;
    
                    var theId =  Meteor.users.findOne()._id;
                     var docs = $("#therelease").find('[name=docId]').val();
    
                      $('#assetlist').css("display","none");
                      $('#uploading').css("display","inherit");
        
     
                      for (var i = 0, ln = files.length; i < ln; i++) {
                              Images.insert(files[i], function (err, fileObj) {
                        if (err) {
        
                         } else {
                                var info = {
                                       docId:docs,
                                     filename:fileObj._id,
                                     type:"featured"
                                      };
            PostAssets.insert(info);
            $('#assetlist').css("display","inherit");
            $('#uploading').css("display","none");
          }
        
        // Inserted new doc with ID fileObj._id, and kicked off the data upload using HTTP
      });
    }
  },`

**Comment by ryanleesipes** [comment]
Reopening, it appears as though this doesn't work with new press releases.

**Comment by bflanagin** [comment]
Oh sweet, I didn't know it could do that. Its working now
