### ISSUE TITLE
Default icons  and placeholder images

### ISSUE THREAD

**Issue by bflanagin** [LeafletBomb/leafletbomb#3]
Some of the spartan-ness of the interface could be solved by having more "alt" images. As we are using a large amounts of fontawesome's assets it would make since to use those where applicable

**Comment by ryanleesipes** [comment]
Let's start removing placeholders as we approach a 1.0 - we can come back later and add functionality, but it'll be good to get this out the door. Placeholders will only make it seem incomplete. Let's simplify and finish what we have. See #22 as an example.
