### ISSUE TITLE
Fix flow of application

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#31]
Sometimes when you submit a form you get popped out in a random place, or what seems like a random place. We need to take note of where these form's submits send users and record them in this issue so that we can adjust that to make it drop folks to the right place.

**Comment by bflanagin** [comment]
Which forms? I think I know which one you're talking about. The press release submit button is the one that annoys me.

**Comment by bflanagin** [comment]
e.preventDefault(); <-- this needs to be added to any form that redirects incorrectly. I'll add them when I'm able.

**Comment by ryanleesipes** [comment]
After a draft is submitted you are popped out to the main area, I think instead you should be directed to the page where you can schedule or publish the draft.

**Comment by bflanagin** [comment]
Agreed and Its fixed now. It also more responsive
