### ISSUE TITLE
Dots where there are no assets (placeholders)

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#32]
Asset dots for un-uploaded assets show in final preview/post. Should avoid showing these dots in place of assets that don't exist and instead show nothing.

![asset_dots](https://user-images.githubusercontent.com/2141621/31415280-9c230f38-addf-11e7-87ba-1958646d2ebd.png)

**Comment by bflanagin** [comment]
Yeah stupid dots.

**Comment by bflanagin** [comment]
Fixed
