### ISSUE TITLE
Form auto fills

### ISSUE THREAD

**Issue by bflanagin** [LeafletBomb/leafletbomb#4]
Some forms could be auto filled based either on setting defaults or by system defaults.

example: Publish date could be set to two weeks after creation, Archive date could be set to one year after the published date.

**Comment by bflanagin** [comment]
Added default dates in date areas

**Comment by ryanleesipes** [comment]
I think you've kind of taken care of this @bflanagin.

**Comment by bflanagin** [comment]
I think you're right
