### ISSUE TITLE
Only View Press Release you are Working On

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#41]
Right now if you click a press release to view/work on. You see all the press releases in alphabetical order in the middle pane.

![press_releases_view](https://user-images.githubusercontent.com/2141621/31512683-14d79a88-af49-11e7-8b0d-9fa95bdd9895.png)

Would like that middle area to display only the press release you are working on.

**Comment by bflanagin** [comment]
Fixed this last night. Does git not tell you that I've updated master?
