### ISSUE TITLE
Featured Image

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#44]
Posts need a featured image, to be included somewhere in the body of the post (and Email). Should be an option on the right-hand side. If it is easy enough to designate one of the assets a "featured image" we should do that. If a solution on that is not easy to implement (i.e. in under 30 minutes), we should simply allow them to upload a featured image.

**Comment by bflanagin** [comment]
Will finish this tomorrow, however I did add the ability to add assets to the release (still needs work)

**Comment by ryanleesipes** [comment]
Great, this is very awesome @bflanagin!

**Comment by bflanagin** [comment]
Need to add the place holder image ,but the feature is complete.

**Comment by ryanleesipes** [comment]
Great, can't wait to see it.

**Comment by bflanagin** [comment]
Done
