### ISSUE TITLE
Update Order of Things in Side Panel

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#46]
@senseiner pointed out a really good observation. We should change the order of things in the right side-panel. See pictures below:

![photo_2017-10-12_20-02-44](https://user-images.githubusercontent.com/2141621/31527096-5fe5e702-af88-11e7-9c6e-e3c17aefcbd9.jpg)

![photo_2017-10-12_20-02-53](https://user-images.githubusercontent.com/2141621/31527102-65c24a44-af88-11e7-9bd3-8400bae52e05.jpg)

**Comment by bflanagin** [comment]
Done,
