### ISSUE TITLE
Rebrand the Landing Page to "Newsroom"

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#48]
The company logo should appear in the top left, with a break and "Newsroom" next to that when someone is viewing the press releases on the influencer side of the site (so when not in the dashboard). On the left-hand side, we need a list of previous press releases with the title and a date. If the whole title does not fit, that's okay, we'll truncate it with some ellipsis, a.k.a. "..." 

The idea is that we won't always be able to capture journalists with an Emailed press release, but when they visit a website they should be able to quickly find a press area with press releases, a press kit, and the like.

**Comment by bflanagin** [comment]
Sounds good

**Comment by bflanagin** [comment]
![screenshot from 2017-10-14 12-27-19](https://user-images.githubusercontent.com/10382037/31577823-24aca3b6-b0db-11e7-9371-adc40b76e4a4.png)

Ugly, but it works.

**Comment by ryanleesipes** [comment]
That looks pretty good. Replace the tag line with the date. It would be good if we could get the featured image to the left of those. But not necessary.

**Comment by bflanagin** [comment]
So it is written, let it be done.

**Comment by bflanagin** [comment]
![screenshot from 2017-10-14 14-30-46](https://user-images.githubusercontent.com/10382037/31578698-4cad6d8a-b0ec-11e7-8ee8-35949fe1bd01.png)

**Comment by ryanleesipes** [comment]
Perfect. Let's circle this up.

**Comment by bflanagin** [comment]
I'm going to assume you mean close it. lol
