### ISSUE TITLE
Adjust Featured Image

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#50]
We have a very cool effect going right now with it, but I think for the featured image to be effective, perhaps it should exist above the press release title, resized to fit atop there. I could see this effect working as you scroll down (if scrolling is required for the length of the press release).

![featured_adjust](https://user-images.githubusercontent.com/2141621/31565294-7958b32c-b023-11e7-9ecf-4c54034d565f.png)

**Comment by bflanagin** [comment]
I like this, but it will required some retooling of things, To make It consistent across all Press Releases the featured image will need a set height. We could use CFS to modify the image once its uploaded. OR demand people upload images with exact dimensions

**Comment by bflanagin** [comment]
I gave this a little more thought, the best way to manage this is to just force a resolution on the user. At least until someone contributes or we find a good inline image editor.

**Comment by bflanagin** [comment]
I've been messing with this, I don't currently have the knowledge on how to make it work the way I think you wanted it. I moved the rest of the post from 280px to 500px which simulates your sample image. I'm sure this can be done. But not by the 17th.

**Comment by bflanagin** [comment]
I'm going to call this closed, I've only run into a few images that look like garbage with the new tweak.
