### ISSUE TITLE
After Setup pop up looks horrible

### ISSUE THREAD

**Issue by bflanagin** [LeafletBomb/leafletbomb#56]
based on ticked #21 I've created a pop up that wont go away till the last few settings are input into the system. The wording and overall look of this pop up is bad. 

Look for and edit SetupNotice.html to make it better.

**Comment by ryanleesipes** [comment]
Is there a way to link them to each part from the pop-up, or better yet force them to do these things during the first-time setup?

**Comment by bflanagin** [comment]
I've moved the logo and trademark selection to the wizard. The other two I can generate from already collected information. We still need some sort of splash screen to encourage user to search the interface.

**Comment by bflanagin** [comment]
Moved to Setup Wizard
