### ISSUE TITLE
No Scheduled Releases/No Published Releases

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#59]
From the dashboard if you click on the "No Scheduled Releases" or "No Published Releases", you get the following page. Might want to make it show something, like a prompt to create a release.

![undefined_no_scheduled](https://user-images.githubusercontent.com/2141621/31951414-4c9fe3c0-b89b-11e7-8e50-8fb2664880bc.png)

**Comment by bflanagin** [comment]
Fixed, Those aren't supposed to be links. But I plan on adding something to the menus if you click on scheduled or drafts .
