### ISSUE TITLE
About Setup Page, "About" disappears

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#60]
The text that says "About" on the About page disappears after just a short moment during initial setup, I'm seeing this on Firefox on elementaryOS.

![about_initial_setup_lb](https://user-images.githubusercontent.com/2141621/31951496-8b7153fe-b89b-11e7-9208-cf883cc2089f.png)

**Comment by bflanagin** [comment]
Not just the "about" but everything above the text area. very strange.

**Comment by bflanagin** [comment]
Its not happening here on Ubuntu / Firefox. Its an odd bug, not sure why it would happen JUST on that page, Can you replicated the issue?

**Comment by ryanleesipes** [comment]
I'll do a Meteor reset and see what I can come up with.

**Comment by bflanagin** [comment]
Weird browser issues. Will re open if we can recreate it on another system.

**Comment by ryanleesipes** [comment]
Disabling Grammarly does fix this problem.
