### ISSUE TITLE
Spelling Error on Backend Email Page

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#62]
"Comming soon" should be "Coming soon", this error is not on the other settings pages.

![backend_settings_comming](https://user-images.githubusercontent.com/2141621/31951840-5cc57dfe-b89c-11e7-8b02-ea17bfb38db3.png)

**Comment by bflanagin** [comment]
Sure that isn't the only one.

**Comment by bflanagin** [comment]
fixed
