### ISSUE TITLE
Attempted Featured Image Showing Up in Wrong Place

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#63]
This one is hard to explain. I tried to change the featured image of a post I was creating using edit, and clicked on the existing featured image - was prompted with a file selection window, chose the image in the picture below. It didn't update the featured image for the post - but apparently, it did change something. The No Schedule Post icon is now what I attempted to set as the featured image for the previous post.

![featured_showed_up_here](https://user-images.githubusercontent.com/2141621/31952328-90205006-b89d-11e7-80c5-cb5ff6f6ef5b.png)

**Comment by bflanagin** [comment]
That...is weird

**Comment by bflanagin** [comment]
Verified, I think I know whats going on shouldn't take but two shakes.

**Comment by bflanagin** [comment]
Fixed, also fixed a bug with adding new assets to the release in edit mode.
