### ISSUE TITLE
Top Bar Goes Transparent After Scrolling

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#64]
After scrolling in on the newsroom page, the top bar becomes transparent. This should remain solid.

![topbar_transparency](https://user-images.githubusercontent.com/2141621/31952346-9b608de6-b89d-11e7-8dcc-5efc1e0edcc0.png)

**Comment by bflanagin** [comment]
I kind of liked it, but its no sweat of my back.
