### ISSUE TITLE
HTML Formatted Press Release (as Email)

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#65]
Make it so that a press release can be formatted as HTML so that the Email appears as the press release does on the website.

In the backend, it might be good to set it so that plain text is still an option, but default should be the pretty looking Email.

**Comment by bflanagin** [comment]
I'm working on the formatting (it was already being sent as html) but I think Gmail is scraping and removing my formatting. I'll keep working at it, see what I can manage.

**Comment by ryanleesipes** [comment]
Took a shot at this in #79

**Comment by ryanleesipes** [comment]
On an Email client on the local machine I could see the featured pic and trademark!

![local_client](https://user-images.githubusercontent.com/2141621/32087694-d929f352-ba9a-11e7-90ed-88eff32b9679.png)

**Comment by bflanagin** [comment]
Still needs some tweaking but its getting CLOSE!

**Comment by bflanagin** [comment]
![screenshot from 2017-10-28 13-18-10](https://user-images.githubusercontent.com/10382037/32137282-8c5e28ec-bbe2-11e7-9013-15290a168295.png)

**Comment by bflanagin** [comment]
I think if we can increase the area in white, maybe by 20% and Fix the black button and either create a button for or get rid of "get press kit". As it does nothing atm.

**Comment by bflanagin** [comment]
The email could use a little more love, but I think it does a good job getting the point across. Till we rework it at a later date.

**Comment by ryanleesipes** [comment]
Will close.
