### ISSUE TITLE
Cheatsheet for formatting

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#66]
Above the editor (main editing area), maybe we should have a button for a cheatsheet that shows a popover with some markdown and however they can use the quotes and attribution, which I think should be changed to double quotes or we could simply use whatever is used for blockquotes, attribution can stay the same.

**Comment by bflanagin** [comment]
We'll need to edit and update this as we add new features to the editor, but for now it will do.
