### ISSUE TITLE
Save and Back (Submit and Cancel)

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#67]
We should change these buttons to be "Save and Back", and I'd love to see them float with the content either at the bottom, top, or side - so that folks don't miss them and realize that they have to press a button to save what they've done.

![submit_and_back](https://user-images.githubusercontent.com/2141621/32007707-8ece4508-b967-11e7-8121-11886ccb6991.png)

**Comment by bflanagin** [comment]
Lets put feedback things in another ticket
