### ISSUE TITLE
No Release on Null

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#70]
We have a problem here where the Release on is still being shown when it is null. I think we just put the date for now with the date it was published (considering release on is still in the works and requires functionality for private press releases).

![release_on_null](https://user-images.githubusercontent.com/2141621/32008479-88b15fbe-b969-11e7-967e-7c1546ad921e.png)

**Comment by bflanagin** [comment]
Hmmmm, Every post gets a date when I try. Could be a hold over from an earlier bug that was squashed.

**Comment by ryanleesipes** [comment]
This is fine, I'm sure. That was a holdover post from an earlier iteration.

**Comment by bflanagin** [comment]
If you edit the post you should be able to add a date. Rest assured its fixed now.
