### ISSUE TITLE
Thin PR post in Newsroom

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#72]
PR posts in the Newsroom seem really stretched out wide, how difficult is it to make that the content area thinner (like 60% instead of something like 80%).

![thin_this_out](https://user-images.githubusercontent.com/2141621/32012936-b9ee38b0-b976-11e7-87c1-76ce195580f6.png)

**Comment by bflanagin** [comment]
Not that hard, the setting can be tweaked in the style sheet under .post I've decreased a bit.  But this is one of those visual tweaks that you'll probably want to mess with till you have it the way you want it.

**Comment by ryanleesipes** [comment]
This is fine. We can adjust it in the future if need be.

**Comment by bflanagin** [comment]
Roger that.
