### ISSUE TITLE
Reverse Order Press Releases

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#73]
Not sure why, but the order of press releases is reversed. It may be because of the lack of a release date for the first one I created.

![reverse_order](https://user-images.githubusercontent.com/2141621/32013046-0c06d846-b977-11e7-89b6-7cf467aa373d.png)

**Comment by bflanagin** [comment]
You're probably right about that hard to sort a null value

**Comment by bflanagin** [comment]
Actually Its not sorting mine either. Could have sworn I fixed this before, but its fixed again
