### ISSUE TITLE
Login Button During Marketer Setup

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#75]
If you click it during marketer setup, it's a problem. (takes you to sign in page, users will not be able to get back to the task at hand, should make login inaccessible during setup).

![login_problem](https://user-images.githubusercontent.com/2141621/32063482-7fa21a8c-ba34-11e7-9277-8c1fbd3867d3.png)

**Comment by bflanagin** [comment]
Fixed
