### ISSUE TITLE
Submit on Influencer Creation Form Not Working

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#77]
The "Cancel" button is working, but the "Submit" button is not (form pictured below).

![submit_not_working](https://user-images.githubusercontent.com/2141621/32064362-cf7e184c-ba36-11e7-8741-76489dfac1e4.png)

**Comment by bflanagin** [comment]
Fixed. I'm currently reworking this section so bugs like that will creep in. The entire area was useless before, now its only kind of useless.
