### ISSUE TITLE
Hide Non-working Feature Placeholders

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#78]
If something doesn't work, hide it. Or put, "Coming Soon" - whatever seems reasonable for the widget.

**Comment by bflanagin** [comment]
Hid the FAQ and Questions areas from companyPage and influencerPage.

**Comment by bflanagin** [comment]
![screenshot from 2017-10-27 12-04-36](https://user-images.githubusercontent.com/10382037/32116183-314071aa-bb0f-11e7-8240-ffd66a4dea49.png)

**Comment by bflanagin** [comment]
Think I have them all
