### ISSUE TITLE
Scheduling and Publishing

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#8]
There should be a "Publish" Button that changes to a "Schedule" button when a date is put in the scheduler.

Let's get a JQuery calendar or something to help folks pick a date for scheduling and publishing.

**Comment by bflanagin** [comment]
JQuery datepicker setup. Defaults for release and archive dates set for the date of creation and one year after that date.

**Comment by ryanleesipes** [comment]
Looks good, but default date is in wrong format (British).

**Comment by bflanagin** [comment]
Fixed the British, added a dialog for more advanced settings (will add  those later).

**Comment by bflanagin** [comment]
Reworked a few things, everything seems to be working
