### ISSUE TITLE
Code on right hand side of influencer

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#82]
What's the code on the right hand side of the influencer?

![code_right_hand_side](https://user-images.githubusercontent.com/2141621/32082152-dbd57f5a-ba76-11e7-92f6-65f19c390b09.png)

**Comment by bflanagin** [comment]
Its debugging stuff. I forgot to remove it when I pushed the update

**Comment by bflanagin** [comment]
Basically if it has to do with #80 assume its there because I was pulled away from finishing that function. AND now branches make sense to me...though its only a problem when you have a team....or users.
