### ISSUE TITLE
Featured Post and Order

### ISSUE THREAD

**Issue by ryanleesipes** [LeafletBomb/leafletbomb#96]
So, here's a bug. The order appears to be correct, with the newest post on top. But the post that appears when I go to the website is not the newest.

**Comment by ryanleesipes** [comment]
Whoops, forgot to add the pic.

![featured_post](https://user-images.githubusercontent.com/2141621/32112931-eb5b891c-bafb-11e7-9476-8811d0abe731.png)

**Comment by bflanagin** [comment]
Must be because its the same date.

**Comment by ryanleesipes** [comment]
Do we track time?

**Comment by bflanagin** [comment]
we track creation date, but that doesn't help us much. I'm going to look into the sorting in mongoDB its given me issues here too. Just a different one.

**Comment by ryanleesipes** [comment]
Awesome, good deal.

**Comment by bflanagin** [comment]
Fixed, added a second sort rule.
